[package]
name = "as-tree"
version = "0.9.0"
authors = ["Jake Zimmerman <zimmerman.jake@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lscolors = "0.7"
